pool:
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'omer-artifactory-saas-platform'
    artifactoryService: 'JFrog Artifactory Instance'
    command: 'jf rt ping'
- task: JFrogPip@1
  inputs:
    artifactoryConnection: 'Omer-JFrogArtifactoryV2'
    command: cd python-example
    command: 'install'
    targetResolveRepo: 'pypi-virtual'
