pool:
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'omer-artifactory-saas-platform'
    artifactoryService: 'JFrog Artifactory Instance'
    command: 'jf rt ping'
- task: JFrogPip@1
  inputs:
    artifactoryConnection: 'Omer-JFrogArtifactoryV2'
    command: 'install'
    arguments: '-r requirements.txt'
    targetResolveRepo: 'pypi-virtual'
    workingDirectory: 'python-example/'
- task: JFrogConan@1
  inputs:
    command: 'which conan; conan --version'