trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'omer-artifactory-saas-platform'
    artifactoryService: 'JFrog Artifactory Instance'
    command: 'jf rt ping'
